# Generated by Django 4.0.2 on 2022-02-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
    ]
