# Generated by Django 4.0.2 on 2022-02-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_person_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
