# Generated by Django 4.0.2 on 2022-02-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0001_initial'),
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='event',
            field=models.ForeignKey(default=b'N', on_delete=django.db.models.deletion.DO_NOTHING, to='events.event'),
        ),
        migrations.AddField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(default=b'N', on_delete=django.db.models.deletion.DO_NOTHING, to='people.person'),
        ),
    ]
