# Generated by Django 4.0.2 on 2022-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_wish_event_wish_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='event',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='owner',
        ),
    ]
