# Generated by Django 4.0.2 on 2022-02-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='desciption',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
